### ISSUE TITLE
Avoid saving files on github repo by default

### ISSUE THREAD

**Issue by Sushil-Thapa** [ThrunGroup/BanditPAM#134]
Currently `data/` folder has two files `mnist.csv`(100 lines, ~2MB) and `MNIST-1k.csv`(1k lines, ~20mb)  saved in Github by default

This can/should be avoided for faster installation(saving time and space). 

Download these datasets only if `env_setup.sh` is executed for `tests` and `development.` 
Since data is already saved on Github  commit history, rewriting git commit history could be one way to purge this from git storage but extremely risky. 

--- 
using `git-lfs` or converting `csv to binary` to use less space could be other alternatives.

**Comment by motiwari** [comment]
Resolved
