### ISSUE TITLE
Cannot install BanditPAM in Paperspace Gradient

### ISSUE THREAD

**Issue by tanweer-mahdi** [ThrunGroup/BanditPAM#170]
Hi! 

I cannot seem to install BanditPAM in the Jupyterlab in a Paperspace Gradient compute instance. I have attached a .txt file with this issue since the error message is way too large. 

Thanks in advance for looking into it. Also thanks for the amazing project you are curating!
[banditpam_error.txt](https://github.com/ThrunGroup/BanditPAM/files/7828937/banditpam_error.txt)

**Comment by motiwari** [comment]
Thanks for the bug report! I'm working on a fix

**Comment by motiwari** [comment]
Hi @tanweer-mahdi , could you please try : `!pip install -vvv banditpam` inside your Gradient instance? It may take a few minutes but should work now. 

I verified this works on a fresh Gradient notebook and does NOT require the paid version of Paperspace:

![image](https://user-images.githubusercontent.com/13426340/148633643-ac94a3ec-42fe-4fb8-8fa2-de462f03974d.png)

By the way, your error message indicates that the installed version of armadillo was too low (we require `armadillo>=10.5.3` specifically for the function `randperm`), so I took care of installing an updated version automatically in Gradient notebooks in the `setup.py`, and fixed a few things so `!pip install banditpam` can be run on Google Colab as well

**Comment by tanweer-mahdi** [comment]
Hi @motiwari , installed and worked like charm! I have to say I am amazed how fast you solved this complex issue! I am working on timeseries clustering with k-Medoids. Hoping to get some good output!

**Comment by motiwari** [comment]
Great, thanks @tanweer-mahdi ! Excited to see your results!
