### ISSUE TITLE
cosine similarity vs cosine distance

### ISSUE THREAD

**Issue by tazitoo** [ThrunGroup/BanditPAM#182]
Wanted to say thanks for the repo - this is a giant leap forward in scaling k-medoids.

I noticed that one of the distance metrics available is cosine similarity - not [cosine distance](https://en.wikipedia.org/wiki/Cosine_similarity) which is 1 - cosine similarity.  My intuition tells me  dist(me, me) should be zero, and not one.  

If using cosine similarity is intentional,  I could put in a PR for cos_dist.

**Comment by motiwari** [comment]
Thanks for the bug report. I have a release going out this week that will address this.

**Comment by motiwari** [comment]
Sorry for the delay. I've fixed this in [6f6de6b](https://github.com/ThrunGroup/BanditPAM/commit/6f6de6b1e429984282deef02784c8c4050c53855), which will go out in a release shortly.

**Comment by tazitoo** [comment]
Awesome - thanks for the quick fix.

...on the lam.
