### ISSUE TITLE
Accept either space-delimited or comma-delimited

### ISSUE THREAD

**Issue by motiwari** [ThrunGroup/BanditPAM#23]
Currently, the BanditPAM source code only accepts space-delimited files. It should also work with comma-delimited files, or with arbitrary delimiters. We should add a parameter to the binary that determines the delimiter, and use space/comma as defaults.

Relevant code: https://github.com/ThrunGroup/BanditPAM/blob/main/src/main.cpp#L56

**Comment by Ben-H3** [comment]
The BanditPAM source code was tested with two files outlining matrices - one using spaces to separate values and the other using commas. The BanditPAM code appeared to properly parse the file and load the array in both cases.

**Comment by motiwari** [comment]
Thanks @Ben-H3 , I tested it myself and indeed found this to be the case. Closing task, I'll assign you another one.
