### ISSUE TITLE
Issue with loading data from numpy array?

### ISSUE THREAD

**Issue by DarioSucic** [ThrunGroup/BanditPAM#32]
Hi,

as part of my thesis I have been implementing the algorithms from this repo from scratch, and I found a discrepancy in the results my code produced when compared to the reference (this repo's Python wrapper).

I debugged the issue for a bit and found that the `data` matrix doesn't match the passed numpy array. This can be seen by printing `data.col(0)` after the transpose on [line 262](https://github.com/ThrunGroup/BanditPAM/blob/main/src/kmedoids_ucb.cpp#L262). We would expect it to return the same point as `X[0]` (where `X` is the numpy array), but instead we get something else. Weirdly enough, the y-coordinate matches, but the x-coordinate is different (and does not appear anywhere in the input data).

To reproduce, insert the following after line 262: 

```cpp
printf("[C++   ] :: X[0] = [%f %f]\n", data.col(0)[0], data.col(0)[1]);
```

then recompile the BanditPAM dependency and run the following Python script:

```python
import numpy as np
from math import dist
from BanditPAM import KMedoids

np.random.seed(0)

means = np.array([[0,0], [-5,5], [5,5]])
X = np.vstack([np.random.randn(2**7, 2) + µ for µ in means])

kmed = KMedoids(n_medoids=3, algorithm="naive", verbosity=0)
kmed.fit(X, "L2", 3, "")

print(f"[Python] :: X[0] = {X[0]}")
```

This gives the following output:

```
[C++   ] :: X[0] = [0.000000 0.400157]
[Python] :: X[0] = [1.76405235 0.40015721]
```

We would expect them to be equal, but they are not. I have not dug deep enough to figure out why this is, though I suspect it is an issue with the C++/Python interfacing libraries. Also possible is that my dependencies are somehow messed up, though that seems unlikely as the issue persists in the BanditPAM version from PyPI, as confirmed by the resulting medoids being identical.

**Comment by motiwari** [comment]
Thanks for filing an issue -- will look into this shortly

**Comment by motiwari** [comment]
@DarioSucic thanks for filing an issue with detailed repro steps.

Strangely, when I follow your suggestions, my C++ and Python values agree -- here's the output of the program you suggest:

```
>>> import numpy as np
>>> from math import dist
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'dist' from 'math' (/opt/intel/oneapi/intelpython/latest/lib/python3.7/lib-dynload/math.cpython-37m-darwin.so)
>>> from BanditPAM import KMedoids
>>>
>>> np.random.seed(0)
>>>
>>> means = np.array([[0,0], [-5,5], [5,5]])
>>> X = np.vstack([np.random.randn(2**7, 2) + µ for µ in means])
>>>
>>> kmed = KMedoids(n_medoids=3, algorithm="naive", verbosity=0)
>>> kmed.fit(X, "L2", 3, "")
[C++   ] :: X[0] = [1.764052 0.400157]
>>>
>>> print(f"[Python] :: X[0] = {X[0]}")
[Python] :: X[0] = [1.76405235 0.40015721]
```

A couple of thoughts:
- Can you make sure you've installed this repo from source via cloning the repo and `pip install .`? It's possible there's a bug in the version currently on PyPi, which doesn't have the latest version yet (working to update shortly)
- If you still see the bug, could you provide details about your OS version, Python version, and pip version?

**Comment by DarioSucic** [comment]
I tried cloning the repo anew and only making the single-line change I described in my post, and the issue persists.

```bash
> pip -V
pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)

> python -V
Python 3.8.5

> gcc --version
gcc (Ubuntu 10.2.0-5ubuntu1~20.04) 10.2.0

> screenfetch -n
 dario@DESKTOP-MJ85PEN
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.4.72-microsoft-standard-WSL2
 Uptime: 17m
 Packages: 890
 Shell: bash 5.0.17
 Disk: 2.7T / 4.2T (65%)
 CPU: AMD Ryzen 9 5900X 12-Core @ 24x 3.7GHz

 RAM: 425MiB / 12737MiB
```

Furthermore, armadillo and carma are both the latest versions found in their respective github repos, and installed using the exact commands from [Dockerfile](https://github.com/ThrunGroup/BanditPAM/blob/main/Dockerfile).

**Comment by motiwari** [comment]
Thanks @DarioSucic , I set up a VM with your build configuration and was able to reproduce the error. Looking into it now.

**Comment by motiwari** [comment]
This seems to be due to an issue in `carma`: https://github.com/RUrlus/carma/issues/63. Will comment on that issue and update here when I have a fix.

**Comment by motiwari** [comment]
Hi @DarioSucic thanks for the bug report. This was due to https://github.com/RUrlus/carma/issues/63. That issue has NOT been fixed in `carma`'s `stable` branch -- the fix only exists in the `unstable` branch.

We've pushed a fix to this repo, where `carma`'s `unstable` branch is now part of this repo. If you do a fresh clone of this repo with `git clone https://github.com/ThrunGroup/BanditPAM.git` and `sudo pip3 install .` from the `BanditPAM` folder, the problem should be fixed. Please reopen this issue if the issue persists.

As an aside -- we copied all of `carma`'s files from the `unstable` branch into this repo, which is obviously suboptimal. If you know the proper way to move it to a git submodule, but one that tracks the `unstable` branch, please let me know.
