### ISSUE TITLE
Duplication of code on loss function

### ISSUE THREAD

**Issue by mailology** [ThrunGroup/BanditPAM#60]
Loss parsing is done on the `main` function in `main.cpp`:
https://github.com/ThrunGroup/BanditPAM/blob/c3f2c77c2891c064b0d71a4628c1846c18714e08/src/main.cpp#L58-L62

as well as in `setLossFn` function in `kmedoids_ucb.cpp`:
https://github.com/ThrunGroup/BanditPAM/blob/c3f2c77c2891c064b0d71a4628c1846c18714e08/src/kmedoids_ucb.cpp#L110-L113

The reason for duplicating the code is because when we call the Python, the main is not called -- we actually create a binding that calls `setLossFn` directly. To avoid duplication, we should have `main` call `setLossFn` function to set the loss function.

**Comment by motiwari** [comment]
Another good find! Think you can fix?
