### ISSUE TITLE
`kmed.fit` should also allow number of medoids to be passed

### ISSUE THREAD

**Issue by motiwari** [ThrunGroup/BanditPAM#78]
In #48 , we removed the capability for users to pass the number of medoids, `k`.

Instead, we should permit the user to both pass the number of medoids to `kmed.fit`, and use the number the `kmed` object was instantiated with if none is passed

**Comment by mailology** [comment]
User can pass number of medoids in both `kmed` object and `kmed.fit`. We can pass `k` to `kmed.fit` to overwrite the number the `kmed` object was instantiated with as demonstrated below:

<img width="1027" alt="Screen Shot 2021-07-31 at 11 37 52 AM" src="https://user-images.githubusercontent.com/25496074/127745093-3e97a392-1b2c-4f38-bb4b-63f4e45b1559.png">

**Comment by motiwari** [comment]
Ah nice, thanks!
