### ISSUE TITLE
Do we actually need `matplotlib` and `pandas` in `requirements.txt`?

### ISSUE THREAD

**Issue by motiwari** [ThrunGroup/BanditPAM#87]
If not, please remove them.

To test if they are necessary, I suggest making a new `virtualenv` without installing `matplotlib` and `pandas` and seeing if you can install from the `setup.py`

**Comment by dhaval737** [comment]
1) Create a new virtual environment
python3 -m venv banditpam
cd banditpam
sorce bin/activate
-------------------
2) Clone the BanditPAM repo
git clone https://github.com/ThrunGroup/BanditPAM.git

-------------------
3)  

(banditpam) % pip list     
Package    Version
---------- -------
pip        10.0.1 
setuptools 39.0.1 
You are using pip version 10.0.1, however version 21.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(banditpam) dhavaldangaria@Dhavals-MacBook-Pro BanditPAM % 

--------------------
4)Removed Matplotlib and Pandas

(banditpam) dhavaldangaria@Dhavals-MacBook-Pro BanditPAM % cat requirements.txt
pybind11>=2.5.0
numpy>=1.16.2
-----------------------

5) Build the BanditPAM

/BanditPAM/: git submodule update --init --recursive
/BanditPAM/: cd headers/carma
/BanditPAM/: mkdir build && cd build && cmake .. && make && sudo make install
/BanditPAM/: cd ../../..
/BanditPAM/: pip install -r requirements.txt
/BanditPAM/: sudo pip install .


---------------------------


Installing collected packages: BanditPAM
  Running setup.py install for BanditPAM ... done
Successfully installed BanditPAM-0.0.35

**Comment by dhaval737** [comment]
Though `matplotlib` and `pandas` are not necessary for the `BanditPAM` installation, they are used in test cases.
